version: '3'
services:

  mongo:
    image: mongo
    restart: always
    command: --quiet --logpath /dev/null --replSet rs0
    environment:
      - MONGO_REPLICA_SET_NAME=rs0 
    volumes:
      - ./chronicle_data:/data/db
    # The following is a hack to sneak in `rs.initiate()` to enable replica sets.
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u admin -p pass --quiet) -eq 1
      interval: 10s
      start_period: 30s

  inx-chronicle:
    depends_on:
      - mongo
      - hornet
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: inx-chronicle:dev
    ports:
      - "8042:8042/tcp"   # REST API
      - "9100:9100/tcp"   # Metrics
    environment:
      - RUST_LOG=warn,inx_chronicle=debug
    tty: true
    command:
      - "--inx"
      - "http://hornet:9029"
      - "--db"
      - "mongodb://mongo:27017"

  hornet:
    image: iotaledger/hornet:2.0.0-alpha.22
    ulimits:
      nofile:
        soft: 8192
        hard: 8192
    stop_grace_period: 5m
    ports:
      - "15600:15600/tcp" # Gossip
      - "14626:14626/udp" # Autopeering
      - "14265:14265/tcp" # REST API
      - "8081:8081/tcp"   # Dashboard
      - "8091:8091/tcp"   # Faucet
      - "9311:9311/tcp"   # Prometheus
      - "9029:9029/tcp"   # INX
    cap_drop:
      - ALL
    volumes:
      - ./hornet_data:/app/alphanet
      - ./config.hornet.json:/app/config.json:ro
    command:
      - "-c"
      - "config.json"
      - "--inx.bindAddress=hornet:9029"
