[alias]
ci-build = "build --all-targets --all-features --release"
ci-clippy = "clippy --all-targets --all-features -- -D warnings"
ci-doctest = "test --doc --all-features --release"
ci-doc = "doc --all-features --no-deps --document-private-items"
ci-fmt = "fmt --all -- --check"
ci-test = "test --all-targets --all-features --release"
ci-toml = "sort --grouped --check"
ci-udeps = "hack --all udeps --all-targets --all-features --backend=depinfo"

fix-clippy = "clippy --all-targets --all-features --fix"
fix-fmt = "fmt --all"
fix-toml = "sort --grouped"
